version: "3.8"
services:
  cache:
    image: redis
    ports:
      - "5573:6379"
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5572:5432"
    environment:
      POSTGRES_PASSWORD: "123456"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - "./volumes/pg:/var/lib/postgresql/data"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - cache
    ports:
      - "5571:8080"
    environment:
      IBGE_BASE_URL: "https://servicodados.ibge.gov.br/api/v1/localidades"
      VIACEP_BASE_URL: "https://viacep.com.br"
      PAN_DB_HOST: "postgres"
      PAN_DB_NAME: "pan_affiliation_api"
      PAN_DB_USERNAME: "postgres"
      PAN_DB_PASSWORD: "123456"
      REDIS_HOST: "cache"
      REDIS_PORT: "6379"
      REDIS_DATABASE: "0"